# -*- coding: utf-8 -*-
"""Aula1_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XRbE5hNVlYEzYeWMUEGmz5o-bMBGcmZY

# **Python paa análise de dados(Pandas)**
"""

# importando a bibliogtec pandas --> pd é apelido
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/dataset/Gapminder.csv", error_bad_lines=False, sep=";")

# Visualizando as 5 primeiras linhas
df.head()

df = df.rename(columns={"country":"Pais", "continent":"Continente", "year":"Ano", "lifeExp":"Expectativa de vida", "pop":"Pop Total", "gdpPercap":"PIB"})

df.head(10)

# Total de linhas e colunas
df.shape

df.columns

df.dtypes

# últimas linhas do arquivo
df.tail(15)

# Informações estatística dos dados do arquivo
df.describe()

df["Continente"].unique()

oceania = df.loc[df["Continente"] == "Oceania"]
oceania.head()

oceania["Continente"].unique()

df.groupby("Continente")["Pais"].nunique()

# Média anual de expectativa de vida
df.groupby("Ano")["Expectativa de vida"].mean()

df["PIB"].mean()

df["PIB"].sum()

