# -*- coding: utf-8 -*-
"""Estrutura_de_dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hT3u93cb6wxtvX2JQSQQF6F044dA4bXt

# **Curso Python Para Análise de dados**

### **Estrutura de dados**
"""

# Criando uma lista chamada animais
animais = [1, 2, 3]
animais

animais = ["cachorro", "gato", 12345, 6.5]
animais

# imprimindo o primeiro elemento da lista
animais[0]

# imprimindo o 4º elemento da llsta
animais[3]

# substituindo o primeiro elemento da lista
animais[0] = "papagaio"
animais[0]

# removendo gato da lista
animais.remove("gato")
animais

len(animais)

"gato" in animais

lista = [500, 300, 300, 80, 10]

max(lista)

min(lista)

animais.append(["leão", "cachorro"])

animais

animais.extend(["cobra", 6])

animais

animais.count("cachorro")

lista.sort()

lista

"""## **Tuplas**"""

# as tuplas usam parênteses como sintaxe
tp = ("Banana","Maçã",10,50)
tp

# retornando o 1º elemento
tp[0]

# diferente das lsitas as tuplas são imutáveis, o que quer dizer não podemos alterar os seus elementos
tp[0] = "Laranja"

tp.count("Maçã")

tp[0:2]

"""## **Dicionários**"""

# para criar um dicionário utilizanos as {}
dc = {"Maçã":20, "Banana":10, "Laanja":15, "Uva":5} # dicionários trabalham com o conceito chave e valor
dc

# acessando o valor de um dicionário através da chave
dc["Maçã"]

# atualizandi o valor de Maçã
dc["Maçã"] = 25
dc

# retornando todaas as chaves do dicionário
dc.keys()

# retornando os valores do dicionário
dc.values()

# verificando se já existe uma chave no dicionário e caso não exista irá inserir
dc.setdefault("Limão", 22)
dc

dc.setdefault("Manga", 30)

dc

dc.setdefault("Uva", 22)

dc

