# -*- coding: utf-8 -*-
"""python_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OuE6YHtWyUlVpoe7L4uPkKaun6R2BTFZ
"""

print("Olá mundo!")

print("Estou aprendendo Python")

"Estou aprendendo Python"

1 + 1

10-2

# este é um comentário em Python

# multiplicação
2 * 8

# divisão
10 / 2

a = 4
b = 6
a + b

# criando uma variável do tipo string
frase = "Python para análise de dados"

print(frase)

frase[0]

frase[0:5]

frase[10:]

frase[:17]

frase.count("dados")

frase.lower()

frase.upper()

frase.replace("Python", "Java")

frase = frase.upper()

frase

